# workflow name
name: Continuous Integration

# fire on
on: [push, pull_request]

#########
# actions
#########
# actions/checkout@v6.0.1
# actions/setup-python@v6.1.0
# rookdev/rookbot/install
# rookdev/rookbot/test

#########
# runners
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
#########
# ubuntu-latest

jobs:
  # Install, List Actions, Discord Notif
  install-list-notif:
    name: 🧮
    runs-on: ${{ matrix.os-name }}
    continue-on-error: True

    strategy:
      matrix:
        os-name: [ ubuntu-latest ]
        python-version: [ "3.13" ]
    steps:
      # checkout commit
      - name: ✔️Checkout commit
        uses: actions/checkout@v6.0.1
      # install python
      - name: 💿Install Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ matrix.python-version }}
      # python version
      - name: 🐍Python Version
        shell: bash
        run: |
          python --version
      # install
      - name: 💿Call Install
        uses: ./.github/actions/install
        with:
          calling-job: install-list-notif
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
      # Analyze used GitHub Actions
      - name: Analyze used GitHub Actions
        shell: bash
        run: |
          python ./resources/ci/common/list_actions.py
      # Send Discord Notification to Updates
      - name: Build Discord Notification Payload
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_UPDATES }}
        run: |
          python ./resources/ci/common/prepare_discord_notif.py
        if: contains(github.ref, 'main') ||
          contains(github.ref, 'stable') ||
          contains(github.ref, 'unstable') ||
          contains(github.ref, 'castIe')

  # Install, Test
  install-test:
    name: ⏱️
    uses: ./.github/workflows/test.yml
    secrets:
      DOTENV_PRIVATE_KEY_DEV_CI: ${{ secrets.DOTENV_PRIVATE_KEY_DEV_CI }}

  # Prepare Pages
  pages-prepare:
    name: 🌎->📦
    runs-on: ${{ matrix.os-name }}
    needs: [install-test]

    strategy:
      matrix:
        os-name: [ ubuntu-latest ]

    steps:
      # checkout commit
      - name: ✔️Checkout commit
        uses: actions/checkout@v6.0.1
      # get parent dir
      - name: 📁Get Parent Directory
        id: parentDir
        uses: ./.github/actions/get-parent-dir
      # Prepare Pages
      - name: 🌎->📦Prepare GitHub Pages
        shell: bash
        run: |
          python ./resources/ci/common/prepare_pages.py
      # upload pages artifact for later step
      - name: 🔼Upload Pages Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          name: pages-${{ matrix.os-name }}
          path: ${{ steps.parentDir.outputs.parentDir }}/pages

  # Deploy Pages
  pages-deploy:
    name: 🌎->🚀
    runs-on: ${{ matrix.os-name }}
    needs: [pages-prepare]

    strategy:
      matrix:
        os-name: [ ubuntu-latest ]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # checkout commit
      - name: ✔️Checkout commit
        uses: actions/checkout@v6.0.1
      # download pages artifact
      - name: 🔽Download Pages Artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: pages-${{ matrix.os-name }}
          path: ./
      # extract pages artifact
      - name: 📂Extract Pages Artifact
        shell: bash
        run: |
          tar xvf artifact.tar
          rm artifact.tar
      # Prepare Differences
      - name: 📝Prepare Differences
        shell: bash
        run: |
          git add .
      # List Differences
      - name: ➖List Differences
        shell: bash
        run: |
          git diff --name-status --cached
      # List commit message
      - name: 📝List Commit Message
        shell: bash
        run: |
          cat commit.txt
      # Push to GH-Pages
      - name: 🚀Push to GH-Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact-name: pages-${{ matrix.os-name }}
        if: contains(github.ref, 'main')
